package com.fzy.minspection.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.fzy.minspection.bean.Item;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ITEM".
*/
public class ItemDao extends AbstractDao<Item, Long> {

    public static final String TABLENAME = "ITEM";

    /**
     * Properties of entity Item.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ItemID = new Property(1, String.class, "ItemID", false, "ITEM_ID");
        public final static Property ModuleID = new Property(2, String.class, "ModuleID", false, "MODULE_ID");
        public final static Property TaskID = new Property(3, String.class, "TaskID", false, "TASK_ID");
    }


    public ItemDao(DaoConfig config) {
        super(config);
    }
    
    public ItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ITEM\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"ITEM_ID\" TEXT," + // 1: ItemID
                "\"MODULE_ID\" TEXT," + // 2: ModuleID
                "\"TASK_ID\" TEXT);"); // 3: TaskID
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ITEM\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Item entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String ItemID = entity.getItemID();
        if (ItemID != null) {
            stmt.bindString(2, ItemID);
        }
 
        String ModuleID = entity.getModuleID();
        if (ModuleID != null) {
            stmt.bindString(3, ModuleID);
        }
 
        String TaskID = entity.getTaskID();
        if (TaskID != null) {
            stmt.bindString(4, TaskID);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Item entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String ItemID = entity.getItemID();
        if (ItemID != null) {
            stmt.bindString(2, ItemID);
        }
 
        String ModuleID = entity.getModuleID();
        if (ModuleID != null) {
            stmt.bindString(3, ModuleID);
        }
 
        String TaskID = entity.getTaskID();
        if (TaskID != null) {
            stmt.bindString(4, TaskID);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Item readEntity(Cursor cursor, int offset) {
        Item entity = new Item( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // ItemID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // ModuleID
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // TaskID
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Item entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setItemID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setModuleID(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTaskID(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Item entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Item entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Item entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
