package com.fzy.minspection.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.fzy.minspection.bean.Module;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MODULE".
*/
public class ModuleDao extends AbstractDao<Module, Long> {

    public static final String TABLENAME = "MODULE";

    /**
     * Properties of entity Module.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ModuleID = new Property(1, String.class, "ModuleID", false, "MODULE_ID");
        public final static Property TaskID = new Property(2, String.class, "TaskID", false, "TASK_ID");
    }


    public ModuleDao(DaoConfig config) {
        super(config);
    }
    
    public ModuleDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MODULE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"MODULE_ID\" TEXT," + // 1: ModuleID
                "\"TASK_ID\" TEXT);"); // 2: TaskID
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MODULE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Module entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String ModuleID = entity.getModuleID();
        if (ModuleID != null) {
            stmt.bindString(2, ModuleID);
        }
 
        String TaskID = entity.getTaskID();
        if (TaskID != null) {
            stmt.bindString(3, TaskID);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Module entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String ModuleID = entity.getModuleID();
        if (ModuleID != null) {
            stmt.bindString(2, ModuleID);
        }
 
        String TaskID = entity.getTaskID();
        if (TaskID != null) {
            stmt.bindString(3, TaskID);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Module readEntity(Cursor cursor, int offset) {
        Module entity = new Module( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // ModuleID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // TaskID
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Module entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setModuleID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTaskID(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Module entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Module entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Module entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
