package com.fzy.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.fzy.db.bean.FzyMessage;

import com.fzy.db.dao.FzyMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fzyMessageDaoConfig;

    private final FzyMessageDao fzyMessageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fzyMessageDaoConfig = daoConfigMap.get(FzyMessageDao.class).clone();
        fzyMessageDaoConfig.initIdentityScope(type);

        fzyMessageDao = new FzyMessageDao(fzyMessageDaoConfig, this);

        registerDao(FzyMessage.class, fzyMessageDao);
    }
    
    public void clear() {
        fzyMessageDaoConfig.clearIdentityScope();
    }

    public FzyMessageDao getFzyMessageDao() {
        return fzyMessageDao;
    }

}
