package com.fzy.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.fzy.db.bean.App1Bean;
import com.fzy.db.bean.App1Bean1;
import com.fzy.db.bean.App2Bean;
import com.fzy.db.bean.App2Bean1;
import com.fzy.db.bean.FzyMessage;

import com.fzy.db.dao.App1BeanDao;
import com.fzy.db.dao.App1Bean1Dao;
import com.fzy.db.dao.App2BeanDao;
import com.fzy.db.dao.App2Bean1Dao;
import com.fzy.db.dao.FzyMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig app1BeanDaoConfig;
    private final DaoConfig app1Bean1DaoConfig;
    private final DaoConfig app2BeanDaoConfig;
    private final DaoConfig app2Bean1DaoConfig;
    private final DaoConfig fzyMessageDaoConfig;

    private final App1BeanDao app1BeanDao;
    private final App1Bean1Dao app1Bean1Dao;
    private final App2BeanDao app2BeanDao;
    private final App2Bean1Dao app2Bean1Dao;
    private final FzyMessageDao fzyMessageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        app1BeanDaoConfig = daoConfigMap.get(App1BeanDao.class).clone();
        app1BeanDaoConfig.initIdentityScope(type);

        app1Bean1DaoConfig = daoConfigMap.get(App1Bean1Dao.class).clone();
        app1Bean1DaoConfig.initIdentityScope(type);

        app2BeanDaoConfig = daoConfigMap.get(App2BeanDao.class).clone();
        app2BeanDaoConfig.initIdentityScope(type);

        app2Bean1DaoConfig = daoConfigMap.get(App2Bean1Dao.class).clone();
        app2Bean1DaoConfig.initIdentityScope(type);

        fzyMessageDaoConfig = daoConfigMap.get(FzyMessageDao.class).clone();
        fzyMessageDaoConfig.initIdentityScope(type);

        app1BeanDao = new App1BeanDao(app1BeanDaoConfig, this);
        app1Bean1Dao = new App1Bean1Dao(app1Bean1DaoConfig, this);
        app2BeanDao = new App2BeanDao(app2BeanDaoConfig, this);
        app2Bean1Dao = new App2Bean1Dao(app2Bean1DaoConfig, this);
        fzyMessageDao = new FzyMessageDao(fzyMessageDaoConfig, this);

        registerDao(App1Bean.class, app1BeanDao);
        registerDao(App1Bean1.class, app1Bean1Dao);
        registerDao(App2Bean.class, app2BeanDao);
        registerDao(App2Bean1.class, app2Bean1Dao);
        registerDao(FzyMessage.class, fzyMessageDao);
    }
    
    public void clear() {
        app1BeanDaoConfig.clearIdentityScope();
        app1Bean1DaoConfig.clearIdentityScope();
        app2BeanDaoConfig.clearIdentityScope();
        app2Bean1DaoConfig.clearIdentityScope();
        fzyMessageDaoConfig.clearIdentityScope();
    }

    public App1BeanDao getApp1BeanDao() {
        return app1BeanDao;
    }

    public App1Bean1Dao getApp1Bean1Dao() {
        return app1Bean1Dao;
    }

    public App2BeanDao getApp2BeanDao() {
        return app2BeanDao;
    }

    public App2Bean1Dao getApp2Bean1Dao() {
        return app2Bean1Dao;
    }

    public FzyMessageDao getFzyMessageDao() {
        return fzyMessageDao;
    }

}
